### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by wispborne** [MagicLibStarsector/MagicLib#36]
https://discord.com/channels/187635036525166592/619635013201428481/1098981241652510800

```
2188312 [Thread-3] INFO  data.scripts.bounty.MagicBountyCoordinator  - Removing expired bounty 'edshipyard_Chupacabra_HVB' (not accepted after 94 days), "High Value Bounty: Euthanize the Chupacabra"
2188313 [Thread-3] INFO  data.scripts.bounty.MagicBountyCoordinator  - Removing expired bounty 'apex_mirror1' (not accepted after 94 days), "Eliminate Dread Pirate Glynda"
2188313 [Thread-3] ERROR data.scripts.edshipyard.rulecmd.ChupacabraAmbushFleetsBountyCommand  - Unable to get MagicBounty: edshipyard_Chupacabra_HVB
java.lang.NullPointerException
	at data.scripts.edshipyard.rulecmd.ChupacabraAmbushFleetsBountyCommand.execute(ChupacabraAmbushFleetsBountyCommand.java:39)
	at com.fs.starfarer.campaign.rules.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.execute(Unknown Source)
	at com.fs.starfarer.campaign.rules.Object.runScript(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.applyRule(FireBest.java:106)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.execute(FireBest.java:51)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.fire(FireBest.java:57)
	at data.scripts.bounty.ActiveBounty.runRuleScript(ActiveBounty.java:363)
	at data.scripts.bounty.ActiveBounty.endBounty(ActiveBounty.java:291)
	at data.scripts.bounty.MagicBountyCoordinator.cleanUpBounties(MagicBountyCoordinator.java:98)
	at data.scripts.bounty.MagicBountyCoordinator.getActiveBounties(MagicBountyCoordinator.java:77)
	at data.scripts.bounty.MagicBountyCampaignPlugin.getBountyKeyForInteractionTarget(MagicBountyCampaignPlugin.java:49)
	at data.scripts.bounty.MagicBountyCampaignPlugin.pickInteractionDialogPlugin(MagicBountyCampaignPlugin.java:25)
	at com.fs.starfarer.campaign.ModAndPluginData$12.super(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.getPriorityPlugin(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.pickInteractionDialogPlugin(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.startEncounterInvolvingPlayerFleet(Unknown Source)
	at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source)
	at com.fs.starfarer.campaign.Hyperspace.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
2188314 [Thread-3] ERROR data.scripts.bounty.MagicBountyCoordinator  - Error removing bounty edshipyard_Chupacabra_HVB
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1459)
	at data.scripts.bounty.MagicBountyCoordinator.cleanUpBounties(MagicBountyCoordinator.java:100)
	at data.scripts.bounty.MagicBountyCoordinator.getActiveBounties(MagicBountyCoordinator.java:77)
	at data.scripts.bounty.MagicBountyCampaignPlugin.getBountyKeyForInteractionTarget(MagicBountyCampaignPlugin.java:49)
	at data.scripts.bounty.MagicBountyCampaignPlugin.pickInteractionDialogPlugin(MagicBountyCampaignPlugin.java:25)
	at com.fs.starfarer.campaign.ModAndPluginData$12.super(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.getPriorityPlugin(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.pickInteractionDialogPlugin(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.startEncounterInvolvingPlayerFleet(Unknown Source)
	at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source)
	at com.fs.starfarer.campaign.Hyperspace.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
2188314 [Thread-3] INFO  sound.public  - Cleaning up music with id [Seeking_Answers.ogg]
2188325 [Thread-7] INFO  sound.public  - Cleaning up music with id [campaign_music_part_2_v28.ogg]
2188475 [Thread-10] INFO  sound.public  - Creating streaming player for music with id [campaign_music_part_2_v28.ogg]
2188476 [Thread-10] INFO  sound.OooO  - Playing music with id [campaign_music_part_2_v28.ogg]
2188800 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at data.scripts.bounty.MagicBountyCoordinator.cleanUpBounties(MagicBountyCoordinator.java:88)
	at data.scripts.bounty.MagicBountyCoordinator.getActiveBounties(MagicBountyCoordinator.java:77)
	at data.scripts.bounty.MagicBountyCampaignPlugin.getBountyKeyForInteractionTarget(MagicBountyCampaignPlugin.java:49)
	at data.scripts.bounty.MagicBountyCampaignPlugin.pickInteractionDialogPlugin(MagicBountyCampaignPlugin.java:25)
	at com.fs.starfarer.campaign.ModAndPluginData$12.super(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.getPriorityPlugin(Unknown Source)
	at com.fs.starfarer.campaign.ModAndPluginData.pickInteractionDialogPlugin(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.startEncounterInvolvingPlayerFleet(Unknown Source)
	at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source)
	at com.fs.starfarer.campaign.Hyperspace.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wispborne** [comment]
No reports, probably caused by other mod?
